function hdrStr = dataHeaders()

    hdr = {...
        't'
        'aero.rho'
        'aero.mach'
        'aero.airspeed'
        'aero.Tinf'
        'ctrlSurf.gear'
        'ctrlSurf.spdbk'
        'ctrlSurf.elevator'
        'ctrlSurf.aileron'
        'ctrlSurf.rudder'
        'ctrlSurf.trim'
        'state.u'
        'state.v'
        'state.w'
        'state.p'
        'state.q'
        'state.r'
        'state.psi'
        'state.theta'
        'state.phi'
        'state.xE'
        'state.yE'
        'state.zE'
        'state.vX'
        'state.vY'
        'state.vZ'
        'state.aX'
        'state.aY'
        'state.aZ'
        'forceMoment.netForceVecInB.X'      % 30
        'forceMoment.netForceVecInB.Y'
        'forceMoment.netForceVecInB.Z'
        'forceMoment.liftVecInB.X'
        'forceMoment.liftVecInB.Y'
        'forceMoment.liftVecInB.Z'
        'forceMoment.dragVecInB.X'
        'forceMoment.dragVecInB.Y'
        'forceMoment.dragVecInB.Z'
        'forceMoment.weightVecInB.X'
        'forceMoment.weightVecInB.Y'
        'forceMoment.weightVecInB.Z'
        'forceMoment.momentVecInB.X'
        'forceMoment.momentVecInB.Y'
        'forceMoment.momentVecInB.Z'
        'FC.dt'                             % 45
        'FC.phase'
        'FC.Sensors.truthSensor.xE'
        'FC.Sensors.truthSensor.yE'
        'FC.Sensors.truthSensor.zE'
        'FC.Sensors.truthSensor.xEdot'
        'FC.Sensors.truthSensor.yEdot'
        'FC.Sensors.truthSensor.zEdot'
        'FC.Sensors.truthSensor.u'
        'FC.Sensors.truthSensor.v'
        'FC.Sensors.truthSensor.w'
        'FC.Sensors.truthSensor.phi'
        'FC.Sensors.truthSensor.theta'
        'FC.Sensors.truthSensor.psi'
        'FC.Sensors.truthSensor.p'
        'FC.Sensors.truthSensor.q'
        'FC.Sensors.truthSensor.r'
        'FC.Sensors.truthSensor.aoa'
        'FC.Sensors.truthSensor.beta'
        'FC.Sensors.IMU.accel.trueBias.X'       % 64
        'FC.Sensors.IMU.accel.trueBias.Y'
        'FC.Sensors.IMU.accel.trueBias.Z'
        'FC.Sensors.IMU.accel.specificForceMsmt.X'
        'FC.Sensors.IMU.accel.specificForceMsmt.Y'
        'FC.Sensors.IMU.accel.specificForceMsmt.Z'
        'FC.Sensors.IMU.gyro.trueBias.X'
        'FC.Sensors.IMU.gyro.trueBias.Y'
        'FC.Sensors.IMU.gyro.trueBias.Z'
        'FC.Sensors.IMU.gyro.omegaMsmt.X'
        'FC.Sensors.IMU.gyro.omegaMsmt.Y'
        'FC.Sensors.IMU.gyro.omegaMsmt.Z'
        'FC.Sensors.GPS.posMsmt.X'
        'FC.Sensors.GPS.posMsmt.Y'
        'FC.Sensors.GPS.posMsmt.Z'
        'FC.Sensors.GPS.velMsmt.X'
        'FC.Sensors.GPS.velMsmt.Y'
        'FC.Sensors.GPS.velMsmt.Z'
        'FC.Navigation.Filters.InertialNavSoln.rpyhat.X'      % 82
        'FC.Navigation.Filters.InertialNavSoln.rpyhat.Y'
        'FC.Navigation.Filters.InertialNavSoln.rpyhat.Z'
        'FC.Navigation.Filters.InertialNavSoln.rhat.X'
        'FC.Navigation.Filters.InertialNavSoln.rhat.Y'
        'FC.Navigation.Filters.InertialNavSoln.rhat.Z'
        'FC.Navigation.Filters.InertialNavSoln.vhat.X'
        'FC.Navigation.Filters.InertialNavSoln.vhat.Y'
        'FC.Navigation.Filters.InertialNavSoln.vhat.Z'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.phi'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.theta'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.psi'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.vX'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.vY'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.vZ'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.rX'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.rY'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.rZ'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.baX'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.baY'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.baZ'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.bgX'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.bgY'
        'FC.Navigation.Filters.IntegratedNavSoln.xhat.bgZ'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.phi'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.theta'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.psi'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.vX'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.vY'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.vZ'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.rX'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.rY'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.rZ'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.baX'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.baY'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.baZ'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.bgX'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.bgY'
        'FC.Navigation.Filters.IntegratedNavSoln.stdev.bgZ'
        'FC.Navigation.Filters.IntegratedNavSoln.biasEstimates.accel.X'       % 121
        'FC.Navigation.Filters.IntegratedNavSoln.biasEstimates.accel.Y'
        'FC.Navigation.Filters.IntegratedNavSoln.biasEstimates.accel.Z'
        'FC.Navigation.Filters.IntegratedNavSoln.biasEstimates.gyro.X'
        'FC.Navigation.Filters.IntegratedNavSoln.biasEstimates.gyro.Y'
        'FC.Navigation.Filters.IntegratedNavSoln.biasEstimates.gyro.Z'
        'FC.Navigation.Filters.IntegratedNavSoln.nextUpdateTime'
        'FC.Navigation.Filters.IntegratedNavSoln.gpsMeasurement.t'
        'FC.Navigation.Filters.IntegratedNavSoln.gpsMeasurement.pos.X'
        'FC.Navigation.Filters.IntegratedNavSoln.gpsMeasurement.pos.Y'
        'FC.Navigation.Filters.IntegratedNavSoln.gpsMeasurement.pos.Z'
        'FC.Navigation.Filters.IntegratedNavSoln.gpsMeasurement.vel.X'
        'FC.Navigation.Filters.IntegratedNavSoln.gpsMeasurement.vel.Y'
        'FC.Navigation.Filters.IntegratedNavSoln.gpsMeasurement.vel.Z'
        'FC.Navigation.ControlVariables.crossTrackError'        % 135
        'FC.Navigation.ControlVariables.crossTrackErrorRate'
        'FC.Navigation.ControlVariables.LonVars.alpha'
        'FC.Navigation.ControlVariables.LonVars.q'
        'FC.Navigation.ControlVariables.LonVars.theta'
        'FC.Navigation.ControlVariables.LatVars.beta'
        'FC.Navigation.ControlVariables.LatVars.p'
        'FC.Navigation.ControlVariables.LatVars.r'
        'FC.Navigation.ControlVariables.LatVars.phi'
        'FC.Navigation.ControlVariables.airspeed'
        'FC.Navigation.ControlVariables.posE.X'     % 145
        'FC.Navigation.ControlVariables.posE.Y'
        'FC.Navigation.ControlVariables.posE.Z'
        'FC.Navigation.ControlVariables.velE.X'
        'FC.Navigation.ControlVariables.velE.Y'
        'FC.Navigation.ControlVariables.velE.Z'
        'FC.Navigation.ControlVariables.posTaem.X'
        'FC.Navigation.ControlVariables.posTaem.Y'
        'FC.Navigation.ControlVariables.posTaem.Z'
        'FC.Navigation.ControlVariables.velTaem.X'
        'FC.Navigation.ControlVariables.velTaem.Y'
        'FC.Navigation.ControlVariables.velTaem.Z'
        'FC.Navigation.ControlVariables.rHac'       % 157
        'FC.Navigation.ControlVariables.psiHac'
        'FC.Navigation.ControlVariables.rdotHac'
        'FC.Guidance.Gains.Vnav.KP'
        'FC.Guidance.Gains.Vnav.KI'
        'FC.Guidance.Gains.Vnav.KD'
        'FC.Guidance.Gains.Lnav.KP'
        'FC.Guidance.Gains.Lnav.KI'
        'FC.Guidance.Gains.Lnav.KD'
        'FC.Guidance.Commands.altitude'
        'FC.Guidance.Commands.theta'
        'FC.Guidance.Commands.phi'
        'FC.Guidance.Commands.airspeed'
        'FC.Guidance.Commands.spdbk'
        'FC.Guidance.Commands.spdbkControllerLevel'
        'FC.Guidance.Integrators.altError'
        'FC.Guidance.Integrators.crossTrackError'
        'FC.Autopilot.Gains.Vnav.K1'        % 174
        'FC.Autopilot.Gains.Vnav.K2'
        'FC.Autopilot.Gains.Vnav.K3'
        'FC.Autopilot.Gains.Vnav.H'
        'FC.Autopilot.Gains.Lnav.K1'
        'FC.Autopilot.Gains.Lnav.K2'
        'FC.Autopilot.Gains.Lnav.K3'
        'FC.Autopilot.Gains.Lnav.K4'
        'FC.Autopilot.Gains.Lnav.H'
        'FC.Autopilot.Integrators.thetaError'
        'FC.Autopilot.Integrators.phiError'
        'FC.ControlSurfCommand.gear'
        'FC.ControlSurfCommand.trim'
        'FC.ControlSurfCommand.elevator'
        'FC.ControlSurfCommand.aileron'
        'FC.ControlSurfCommand.rudder'
        'FC.ControlSurfCommand.spdbk'
        'wind.windN'
        'wind.windE'
        'wind.windD'
        'wind.windU'
        'wind.windV'
        'wind.windW'
    };

    hdrStr = [];

    for idx = 1:numel(hdr)
        hdrStr = [hdrStr, hdr{idx}, ','];
    end
    
    hdrStr(end) = [];


end